language: python
python:
    - "3.6"
before_install:
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - coverage run --source sc -m pytest
after_success:
  - coverage report -m
