language: python
python:
    - "3.6"
before_install:
  - pip install -r requirements.txt
install:
  - python setup.py install
script:
  - python -m coverage run --source sc -m pytest
after_success:
  - python -m coverage report -m
  - coveralls
